package box

import (
	"fmt"
	"strings"
)

// What a box is built from. These are constants rather than "whatever is
// current at the time", because a run has to be reproducible and a surprise
// major version is not a thing to discover four hours in.
//
// Keep them current. A box is created fresh for every run and thrown away
// afterwards, so raising one of these costs nothing, and letting them rot means
// every run for months works against a runtime nobody develops against any more.
const (
	// DefaultImage is the Hetzner image name. Ubuntu 26.04 LTS (Resolute
	// Raccoon) has been the current LTS since August 2026, and it is what makes
	// the list below as short as it is: it ships PHP 8.5 and PostgreSQL 18, both
	// current, so neither needs a third-party repository.
	DefaultImage = "ubuntu-26.04"
	// phpSeries is the PHP the image ships, and therefore the prefix its
	// extension packages carry. A project that needs a different one installs it
	// from its own setup; the base is deliberately the distribution's.
	phpSeries = "8.5"
	// nodeMajor is the active Node LTS line, from NodeSource because Ubuntu's
	// own Node is a release behind. Claude Code does not need it — it installs
	// as a native binary — so this is here purely for the projects that do,
	// which for a Laravel app means the asset pipeline.
	nodeMajor = "24"
	// claudeChannel is the Claude Code release channel. "stable" runs about a
	// week behind and skips releases with known major regressions, which is the
	// right side of that trade for a machine that will run unattended for hours
	// with permissions skipped.
	claudeChannel = "stable"
)

// cloudInitOptions are the few things about a box that are not the same for
// every one of them.
type cloudInitOptions struct {
	// Hostname is what the box calls itself, which is what the prompt shows when
	// you ssh in wondering which machine you are on.
	Hostname string
	// ExtraPackages are apt packages a project asks for on top of the base.
	ExtraPackages []string
}

// cloudInit renders the cloud-config that turns a bare Ubuntu instance into one
// a run can happen on.
//
// It installs the base only: the language runtimes, the database, the agent CLI,
// and the systemd unit a run is started as. Everything a specific project needs
// — its dependencies, its schema, its .env — belongs in that project's
// `worktree.setup`, which chief runs inside the checkout before the agent
// starts. The split matters because this is baked into the instance when it is
// created and a project's needs change weekly.
func cloudInit(opts cloudInitOptions) string {
	var extra strings.Builder
	for _, p := range opts.ExtraPackages {
		if p = strings.TrimSpace(p); p != "" {
			fmt.Fprintf(&extra, "\n  - %s", p)
		}
	}

	// Rendered with Sprintf rather than text/template: the substitutions are
	// three version numbers and a hostname, and a template would put a layer of
	// {{ }} between this file and the shell it is trying to read as.
	return fmt.Sprintf(`#cloud-config
# Generated by chief (internal/box/cloudinit.go). Provisions a throwaway
# instance to the point where "chief start --headless" can run on it.

hostname: %[4]s
preserve_hostname: false

package_update: true
package_upgrade: false

packages:
  - git
  - curl
  - jq
  - unzip
  - rsync
  - build-essential
  - ripgrep
  - gnupg
  # PHP %[1]s and PostgreSQL, both the versions the image ships, both current.
  # The extension list is the one a Laravel app fails to boot without.
  - php%[1]s-cli
  - php%[1]s-curl
  - php%[1]s-mbstring
  - php%[1]s-xml
  - php%[1]s-zip
  - php%[1]s-bcmath
  - php%[1]s-intl
  - php%[1]s-pgsql
  - php%[1]s-sqlite3
  - php%[1]s-gd
  # A run's test database is local to the instance; it has no business anywhere
  # else.
  - postgresql
  - postgresql-contrib
  - redis-server%[5]s

write_files:
  - path: /etc/sudoers.d/chief
    permissions: "0440"
    content: |
      chief ALL=(ALL) NOPASSWD:ALL

  # Where the tokens land. Created empty and locked down first, so there is no
  # window in which it exists world-readable.
  - path: /home/chief/.chief-env
    owner: chief:chief
    permissions: "0600"
    content: |
      # filled in by chief once the instance is up

  # The unit a run is started as. One-shot rather than a service that restarts:
  # a chief run that ended has ended, and starting it again from the top is a
  # decision for a person to make.
  - path: /etc/systemd/system/chief-run@.service
    permissions: "0644"
    content: |
      [Unit]
      Description=chief headless run (%%i)
      After=network-online.target postgresql.service
      Wants=network-online.target

      [Service]
      Type=oneshot
      User=chief
      WorkingDirectory=/home/chief/project
      EnvironmentFile=/home/chief/.chief-env
      # A run is measured in hours and must never be cut short by a timeout.
      TimeoutStartSec=infinity
      # systemd stops a unit with SIGTERM, which chief turns into a clean stop:
      # the agent is killed, its commits stay. The grace period is for the agent
      # process tree to actually go away.
      KillSignal=SIGTERM
      TimeoutStopSec=120
      ExecStart=/bin/sh -c '/usr/local/bin/chief start %%i --headless $CHIEF_RUN_FLAGS'
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target

users:
  # Work does not happen as root: the agent runs with permissions skipped, and
  # there is no reason to hand it the whole machine as well.
  - name: chief
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: []

runcmd:
  # Give the chief user the key the instance was created with, so nothing has to
  # run as root to get work done.
  - mkdir -p /home/chief/.ssh
  - cp /root/.ssh/authorized_keys /home/chief/.ssh/authorized_keys
  - chown -R chief:chief /home/chief/.ssh
  - chmod 700 /home/chief/.ssh
  - chmod 600 /home/chief/.ssh/authorized_keys

  # Claude Code, from Anthropic's signed apt repository rather than the curl
  # installer or npm: unattended provisioning should not pipe a downloaded
  # script into a shell when a signed package is on offer. The key's fingerprint
  # is 31DDDE24DDFAB679F42D7BD2BAA929FF1A7ECACE.
  - install -d -m 0755 /etc/apt/keyrings
  - curl -fsSL https://downloads.claude.ai/keys/claude-code.asc -o /etc/apt/keyrings/claude-code.asc
  - gpg --show-keys --with-colons /etc/apt/keyrings/claude-code.asc | grep -q 31DDDE24DDFAB679F42D7BD2BAA929FF1A7ECACE
  - echo "deb [signed-by=/etc/apt/keyrings/claude-code.asc] https://downloads.claude.ai/claude-code/apt/%[3]s %[3]s main" > /etc/apt/sources.list.d/claude-code.list

  # The GitHub CLI, for the pull request a finished run opens.
  - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg -o /etc/apt/keyrings/githubcli.gpg
  - chmod 644 /etc/apt/keyrings/githubcli.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list

  # Node %[2]s, for the projects that need it.
  - curl -fsSL https://deb.nodesource.com/setup_%[2]s.x | bash -

  - apt-get update
  - apt-get install -y claude-code gh nodejs

  # Composer.
  - curl -fsSL https://getcomposer.org/installer -o /tmp/composer-setup.php
  - php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - rm -f /tmp/composer-setup.php

  # A database superuser named after the account that will use it, so a project's
  # setup script can create and drop its own databases without a password.
  - su - postgres -c "psql -c \"CREATE ROLE chief WITH LOGIN SUPERUSER PASSWORD 'chief'\"" || true
  - su - postgres -c "createdb -O chief chief" || true

  - systemctl daemon-reload
  # The marker chief waits for. Written last, so its existence means every step
  # above finished.
  - touch /var/lib/cloud/chief-ready

final_message: "chief box ready after $UPTIME seconds"
`, phpSeries, nodeMajor, claudeChannel, opts.Hostname, extra.String())
}
